# Generated by Django 4.1 on 2022-09-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mywatchlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mywatchlist",
            name="rating",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="mywatchlist",
            name="release_date",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="mywatchlist",
            name="watched",
            field=models.BooleanField(default=False),
        ),
    ]
